pretrained_model_name_or_path: 'pretrained/Era3D-512-6view'
revision: null

num_views: 6
validation_dataset:
  prompt_embeds_path: mvdiffusion/data/fixed_prompt_embeds_6view
  root_dir: 'examples'
  num_views: ${num_views}
  bg_color: 'white'
  img_wh:  [512, 512]
  num_validation_samples: 1000
  crop_size: 420

pred_type: 'joint'
save_dir: 'mv_res'
save_mode: 'rgba' # 'concat', 'rgba', 'rgb'
seed: 42
validation_batch_size: 1
dataloader_num_workers: 1 
local_rank: -1

pipe_kwargs:
  num_views: ${num_views}

validation_guidance_scales: [3.0]
pipe_validation_kwargs:
  num_inference_steps: 40
  eta: 1.0

validation_grid_nrow: ${num_views}
regress_elevation: true
regress_focal_length: true
unet_from_pretrained_kwargs:
  unclip: true
  sdxl: false
  num_views: ${num_views}
  sample_size: 64 
  zero_init_conv_in: false # modify
  
  regress_elevation: ${regress_elevation}
  regress_focal_length: ${regress_focal_length}
  camera_embedding_type: e_de_da_sincos
  projection_camera_embeddings_input_dim: 4 # 2 for elevation and 6 for focal_length  
  zero_init_camera_projection: false
  num_regress_blocks: 3
  
  cd_attention_last: false
  cd_attention_mid: false
  multiview_attention: true
  sparse_mv_attention: true
  selfattn_block: self_rowwise
  mvcd_attention: true

  use_dino: false

enable_xformers_memory_efficient_attention: true