name: "3DTopia__base2_step_4__asd_mv+rd+sd_volsdf+diffmc-0_full_dmd_v3"
tag: "${rmspace:${data.prompt_library},_}"
exp_root_dir: "outputs_9"
seed: 0

data_type: "multiview-multiprompt-dualrenderer-multistep-datamodule-v2"
data:
  batch_size: 4 # should be the multiple of n_views
  n_view: 4 
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: 512
  height: 512 # so high resolution !!
  ray_height: 64
  ray_width: 64
  # unsupervised data
  prompt_library: ???
  unsup_elevation_range: [0, 30]
  unsup_camera_distance_range: [0.8, 1.0] # relative
  unsup_fovy_range: [15, 60]
  relative_radius: true
  eval_camera_distance: 3.0
  eval_fovy_deg: 40.
  n_val_views: 40
  n_test_views: 120
  # supervised data
  obj_library: "none"
  meta_json: "none"
  rgb_data_dir: "none"
  normal_data_dir: "none"
  depth_data_dir: "none"
  camera_data_dir: "none"
  frontal_idx: 24 # 24 is the frontal view
  # the sup / unsup ratio, for training
  sup_unsup_mode: "vanilla" # "vanilla"
  dim_gaussian: [6, 4, 32, 32] # not used
  pure_zeros: false
  # for training
  n_steps: ${system.num_parts_training}

  guidance_processor_type: "dual-stable-diffusion-multi-prompt-processor-callable"
  guidance_processor:
    spawn: true
    pretrained_model_name_or_path: "pretrained/stable-diffusion-v1-5" # used by RichDreamer
    negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    pretrained_model_name_or_path_2nd: "pretrained/stable-diffusion-2-1-base" # used by MVDream, will be processed by condition_processor
    negative_prompt_2nd: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, and unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions"
    use_local_text_embeddings: true

  condition_processor_type: "stable-diffusion-multi-prompt-processor-callable"
  condition_processor:
    spawn: true
    pretrained_model_name_or_path: ${system.geometry.space_generator_config.pretrained_model_name_or_path}
    negative_prompt: ""
    use_local_text_embeddings: true

system_type: "multiprompt-dual-renderer-multistep-generator-system"
system:
  initialize_shape: false # #true #
  visualize_samples: false 
  parallel_guidance: true

  # multi-step trianing / inference
  num_parts_training: 4 # TBD
  num_steps_training: 4 # TBD
  num_steps_sampling: 4
  noise_scheduler: "ddim" 
  sample_scheduler: "ddim" 
  noise_addition: "gaussian" # TBD, any of "gaussian", "zero", "pred"

  scheduler_dir: ${system.geometry.space_generator_config.pretrained_model_name_or_path}
  specifiy_guidance_timestep: null # any of null, v1
  predition_type: "epsilon" # any of "epsilon", "sample", "sample_delta", "sample_delta_v2"

  geometry_type: "one-step-triplane-dual-stable-diffusion"
  geometry:
    radius: 1. 
    normal_type: "analytic"

    sdf_bias: sphere
    sdf_bias_params: 0.5 # a small bias will be fine?

    rotate_planes: v2
    space_generator_config:
      pretrained_model_name_or_path: "pretrained/stable-diffusion-2-1-base"
      timestep: 999
      output_dim: 32

      training_type: "full"
      # training_type: "self_lora_rank_96-cross_lora_rank_16-locon_rank_16" 
      # self_lora_type: "vanilla"
      # cross_lora_type: "vanilla"
      # locon_type: "vanilla_v1"


      prompt_bias: true
      prompt_bias_lr_multiplier: 1

      # gradient_checkpoint: true

    isosurface_deformable_grid: true


  material_type: no-material
  material:
    n_output_dims: 3
    requires_normal: true
    color_activation: sigmoid-mipnerf # follow OpenLRM


  background_type: "multi-prompt-neural-hashgrid-environment-map-background"
  background:
    color_activation: sigmoid-mipnerf # follow OpenLRM
    random_aug: false
    eval_color: [1., 1., 1.]



  renderer_type: generative-space-dmtet-rasterize-renderer
  renderer:
    radius: ${system.geometry.radius}
    isosurface_remove_outliers: false
    isosurface_method: "diffmc"
    enable_bg_rays: true
    sdf_grad_shrink: 0. #[0, 0.1, 1., 30000]
    allow_empty_flag: false


  renderer_2nd_type: generative-space-volsdf-volume-renderer
  renderer_2nd:
    radius: ${system.geometry.radius}
    use_volsdf: true
    trainable_variance: false # important!
    learned_variance_init: 0.3401 # 0.3401 = log(30) / 10, 40 is the most common variance across the prompts

    # randomized: false

    estimator: importance
    num_samples_per_ray: 64
    num_samples_per_ray_importance: 128
    near_plane: 0.1
    far_plane: 4.0
    train_chunk_size: 0 #100000

  guidance_type: "richdreamer-mvdream-stablediffusion-asynchronous-score-distillation-guidance"
  guidance:
    min_step_percent: [0, 0.5, 0.02, 30000]
    max_step_percent: [0, 0.98, 0.5, 30000]

    # the following are specific to MV
    mv_model_name_or_path: "sd-v2.1-base-4view"
    mv_ckpt_path: "pretrained/sd-v2.1-base-4view.pt" 
    mv_weight: 3.
    mv_guidance_scale: 7.5 #7.5
    mv_weighting_strategy: "dmd"

    # the following are specific to RD
    rd_min_step_percent: 0.5
    rd_max_step_percent: 0.98
    rd_model_name_or_path: "nd-mv"
    rd_ckpt_path: "pretrained/nd_mv_ema.ckpt"
    rd_weight: 3.
    rd_guidance_scale: 7.5
    rd_weighting_strategy: "sds_sqrt"
    # cam_method: "rel_x2" # "rel_x2", "rel" or "abs"

    rd_use_sds: false
    # cam_method: "rel_x2" # "rel_x2", "rel" or "abs"

    # the following are specific to SD
    sd_model_name_or_path: "pretrained/stable-diffusion-2-1-base"
    sd_weight: [0, 0.1, 1., 30000]
    sd_guidance_scale: 7.5
    sd_weighting_strategy: "dmd"

    # the following are specific to ASD
    plus_schedule: "linear"
    # the following are specific to the combination of ASD with MV and SD
    mv_plus_random: true
    mv_plus_ratio: 0.1
    rd_plus_random: true
    rd_plus_ratio: 0.1
    sd_plus_random: true
    sd_plus_ratio: 0.1

    # try to save memory cost
    gradient_checkpoint: true
    auto_grad: true



  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    weighting_strategy: "v1" 

    lambda_asd: 1.
    lambda_orient: 0.
    lambda_sparsity: 0
    lambda_opaque: 0 
    lambda_z_variance: 0.
    lambda_eikonal: 0.
    lambda_normal_consistency: 0.
    lambda_laplacian_smoothness: 0.
    lambda_normal_smoothness_2d: 0.
    lambda_sdf_abs: 0.

    lambda_asd_2nd: 1.
    lambda_orient_2nd: 0.
    lambda_sparsity_2nd: 1.
    lambda_opaque_2nd: 0. 
    lambda_z_variance_2nd: 0.
    lambda_eikonal_2nd: 1.
    lambda_normal_consistency_2nd: 0.
    lambda_laplacian_smoothness_2nd: 0.
    lambda_normal_smoothness_2d_2nd: 0. 
    lambda_sdf_abs_2nd: 0. # should not be used!

  optimizer:
    name: Adan # for fast convergence
    args:
      betas: [0.98, 0.92, 0.99]
      eps: 1.e-15
    params:
      geometry:
        lr: 0.0002 # 0.002
      background:
        lr: 0.0002 # 0.002


trainer:
  max_steps: 500000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 10000
  # check_val_every_n_epoch: 50
  enable_progress_bar: true
  precision: 32
  strategy: "ddp" #"ddp_find_unused_parameters_true" # "deepspeed_stage_2"
  accumulate_grad_batches: 1 # > 1 is not supported

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.val_check_interval}
  # every_n_epochs: ${trainer.check_val_every_n_epoch}
